### PR TITLE
Bg feedback #161412228

### PR DESCRIPTION
**Pull request by calvinpete**
@AtamaZack @armstrongsouljah @pbkabali @chrismatgit @NabunyaLilian
Hey, everyone, check out the changes I made in response to the feedback.
**Log in link:** https://calvinpete.github.io/StoreManager/templates/login.html
To log in as Admin, please fill in **admin** for admin username and **pass** for admin password
To log in as a normal user, please fill in **user** for username and **pass** for password

### CODE REVIEW

**Comment by NabunyaLilian** [comment]
Great work on your site it looks good, though there are some things I'm suggesting;
- When I want to log in as an admin, I don't think I should have an option of signing up because anyone could click there and create there own account which is not good practice. 
- I suggest you put icons on the panels you have like sales Records, new store attendants, and also the user's side too.
- Consider making the action part options as buttons.
- Also, put icons on the user's profile to make it look more attractive
- you could also try to put each text input on 1 line in register staff Attendant.

**Comment by armstrongsouljah** [comment]
Nice job on the dashboard. I would however suggest that you ensure the form
background covers the form on the mobile view. The login fields span iut of
their container, the background. Please consider rectifying that.

**Comment by calvinpete** [comment]
Thank you, let me work on those.

**Comment by pbkabali** [comment]
Nice work, good color schemes,  can see the intended logic. Good job

**Pull request closed without merging**
